using Application.API.Service;
using Application.Data.DTOs;
using Application.Data.Enums;
using Application.Data.Models;
using Application.Data.Repositories;
using Application.Data.Repositories.IRepository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;

namespace Application.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class UserController : ControllerBase
    {
        private readonly IUser UserRepo;
        private readonly IImageRepository ImageRepo;
        public UserController(IUser UserRepo, IImageRepository ImageRepo)
        {
            this.UserRepo = UserRepo;
            this.ImageRepo = ImageRepo;
        }

        [HttpGet]
        public async Task<ActionResult<List<User>>> Get()
        {
            return await UserRepo.GetUsers();
        }

        [HttpGet("{ID}")]
        public async Task<ActionResult<User?>> Get(Guid ID)
        {
            return await UserRepo.GetUserByID(ID);
        }

        [HttpPost]
        public async Task<ActionResult<User>> Post([FromForm] UserDTO NewUser, IFormFile? ProfilePic)
        {
            if (ProfilePic != null)
            {
                switch (ImageUploaderValidator.ValidateImageSizeAndHeader(ProfilePic, 4_194_304))
                {
                    case ErrorResult.IMAGE_TOO_BIG_ERROR:
                        return BadRequest($"Tệp ảnh không được vượt quá {4_194_304 / 1_048_576}MB!");
                    case ErrorResult.IMAGE_IS_BROKEN_ERROR:
                    default:
                        return BadRequest("Tệp ảnh không hợp lệ!");
                    case SuccessResult.IMAGE_OK:
                        {
                            ImageDTO AutoGeneratedImageInfo = new() { Status = 1 };
                            if (string.IsNullOrWhiteSpace(NewUser.FirstName) ||
                                string.IsNullOrWhiteSpace(NewUser.LastName))
                            {
                                AutoGeneratedImageInfo.ImageName = $"Ảnh của {NewUser.Username}";
                                AutoGeneratedImageInfo.ImageDescription = $"Ảnh đại diện của người dùng {NewUser.Username}";
                            }
                            else
                            {
                                AutoGeneratedImageInfo.ImageName = $"Ảnh của {NewUser.LastName} {NewUser.FirstName}";
                                AutoGeneratedImageInfo.ImageDescription = $"Ảnh đại diện {NewUser.LastName} {NewUser.FirstName}";
                            }
                            
                            var CreatedImage = await ImageRepo.CreateImageAsync(AutoGeneratedImageInfo, ProfilePic);

                            NewUser.ImageID = CreatedImage.ImageID;
                        }
                    break;
                }
            }
            var Response = await UserRepo.CreateUser(NewUser);
            return CreatedAtAction(nameof(Get), new { ID = Response.UserID }, Response);
        }

        [HttpPut("{ID}")]
        public async Task<ActionResult<User?>> Put(Guid ID, [FromForm] UserDTO UpdatedUser, IFormFile? ProfilePic)
        {
            if (ProfilePic != null)
            {
                switch (ImageUploaderValidator.ValidateImageSizeAndHeader(ProfilePic, 4_194_304))
                {
                    case ErrorResult.IMAGE_TOO_BIG_ERROR:
                        return BadRequest($"Tệp ảnh không được vượt quá {4_194_304 / 1_048_576}MB!");
                    case ErrorResult.IMAGE_IS_BROKEN_ERROR:
                    default:
                        return BadRequest("Tệp ảnh không hợp lệ!");
                    case SuccessResult.IMAGE_OK:
                        {

                            ImageDTO AutoGeneratedImageInfo = new() { Status = 1 };
                            if (string.IsNullOrWhiteSpace(UpdatedUser.FirstName) ||
                                string.IsNullOrWhiteSpace(UpdatedUser.LastName))
                            {
                                AutoGeneratedImageInfo.ImageName = $"Ảnh của {UpdatedUser.Username}";
                                AutoGeneratedImageInfo.ImageDescription = $"Ảnh đại diện của người dùng {UpdatedUser.Username}";
                            }
                            else
                            {
                                AutoGeneratedImageInfo.ImageName = $"Ảnh của {UpdatedUser.LastName} {UpdatedUser.FirstName}";
                                AutoGeneratedImageInfo.ImageDescription = $"Ảnh đại diện {UpdatedUser.LastName} {UpdatedUser.FirstName}";
                            }
                            var CreatedImage = await ImageRepo.CreateImageAsync(AutoGeneratedImageInfo, ProfilePic);

                            UpdatedUser.ImageID = CreatedImage.ImageID;
                        }
                        break;
                }
            }
            return await UserRepo.UpdateUser(ID, UpdatedUser);
        }

        [HttpDelete("{ID}")]
        public async Task<ActionResult> Delete(Guid ID)
        {
            await UserRepo.DeleteUser(ID);
            return Ok();
        }
    }
}
